version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "15671:15671"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=newhire
      - RABBITMQ_DEFAULT_PASS=ultimate

