version: '3'
services:
  producer:
    build: ./producer
    ports: 
      - "9090:9090"
    container_name: producer
  consumer:
    build: ./consumer
    ports: 
      - "8080:8080"
    container_name: consumer
  rabbit:
    image: rabbitmq:3-management
    container_name: my-rabbit
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=newhire
      - RABBITMQ_DEFAULT_PASS=ultimate

